use_frameworks!

platform :ios, '10.0'

target 'UKThreadSafeObjc_Example' do
  pod 'UKThreadSafeObjc', :path => '../'

  target 'UKThreadSafeObjc_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
